Update Finetuning_Granite_Pirate_Style.ipynb
Minor change to avoid the following exception:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Note: this is already done properly for the second `tokenizer()` call.

Signed-off-by: Gonéri Le Bouder <goneri@lebouder.net>
Signed-off-by: BJ Hargrave <bj@hargrave.dev>